### ISSUE TITLE
Fix_fft

### ISSUE THREAD

**Issue by funfrancis** [TJC/arduino#1]
Hi

I copied the fix_fft.h and fix_fft.cpp file onto the library folder in arduino

I uploaded the example sketch
`#include <fix_fft.h>

char im[128];
char data[128];

void setup(){
 Serial.begin(9600);
}

void loop(){
  int static i = 0;
  static long tt;
  int val;

   if (millis() > tt){
    if (i < 128){
      val = analogRead(0);
      data[i] = val / 4 - 128;
      im[i] = 0;
      i++;  

```
}
else{
  //this could be done with the fix_fftr function without the im array.
  fix_fft(data,im,7,0);
  // I am only interessted in the absolute value of the transformation
  for (i=0; i< 64;i++){
     data[i] = sqrt(data[i] * data[i] + im[i] * im[i]);
  }

  //do something with the data values 1..64 and ignore im
  show_big_bars(data,0);
}

tt = millis();
```

   }
} 

/*

this should give an fft with 
- sampling rate:           1ms
- frequency range: - 7.8 to 500 Hz in 64 7.8hz bands

there is a lot that can be improved:
- fix bugs
- replace FIX_MPY by inline assembler
- do sampling with timer and interrupts
- use fix_fftr instead of fix_fft to save ram (i did not get the math right)

*/`

But get error
`'show_big_bars' was not declared in this scope`

How do I debug it??

Pls help!!!

**Comment by TJC** [comment]
Hey, I kinda copied that code from somewhere else myself and made it fit into my code -- which wasn't really intended to be a public library.
If you search around on Google you should be able to find the original FFT code, and then use that instead?
Or have a look at PJRC's Audio library, that's really good too and includes FFTs

**Comment by funfrancis** [comment]
Is it possible for you tpo draft a simple FFT code for arduino that does not make use of any libraries but works the way it is to work 

I need it for integrating the LoRa telemetry with Arduino to send the FFT data to the base station and the issue is that the LoRa system is incompatible with most of Arduino's Libraries

Pls help me!!!

**Comment by TJC** [comment]
I'm trying to push you in the right direction; see my previous comment.

If you'd like to engage me as a contracted software developer on your project, please contact by email with the scope of work and the rates of pay you're offering. 

But otherwise -- this "Arduino" package of mine on Github doesn't come with any warranty or support. You're welcome to look at my code, but it's not MEANT for public consumption, and I am way too busy to help everyone on the internet with their random projects.
